-- ============================================================
-- GOLDEN FRONT: COMMAND 3.2.0
-- FULL SUPABASE DATABASE SETUP
-- Run this entire file once in Supabase SQL Editor.
-- ============================================================

-- ------------------------------------------------------------
-- 1) PLAYER SAVES
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.player_saves (
    user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    save_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.player_saves ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "player_saves_select_own" ON public.player_saves;
DROP POLICY IF EXISTS "player_saves_insert_own" ON public.player_saves;
DROP POLICY IF EXISTS "player_saves_update_own" ON public.player_saves;
DROP POLICY IF EXISTS "player_saves_delete_own" ON public.player_saves;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.player_saves TO authenticated;

CREATE POLICY "player_saves_select_own"
ON public.player_saves FOR SELECT TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY "player_saves_insert_own"
ON public.player_saves FOR INSERT TO authenticated
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "player_saves_update_own"
ON public.player_saves FOR UPDATE TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "player_saves_delete_own"
ON public.player_saves FOR DELETE TO authenticated
USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS player_saves_updated_at_idx
ON public.player_saves(updated_at);


-- ------------------------------------------------------------
-- 2) ONLINE COUNTRY CLAIMS
-- One country per server, and one country per player per server.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.online_country_claims (
    server_id INTEGER NOT NULL DEFAULT 1,
    country_iso TEXT NOT NULL,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    claimed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (server_id, country_iso),
    UNIQUE (server_id, user_id)
);

ALTER TABLE public.online_country_claims ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "country_claims_select" ON public.online_country_claims;
DROP POLICY IF EXISTS "country_claims_insert" ON public.online_country_claims;
DROP POLICY IF EXISTS "country_claims_delete" ON public.online_country_claims;

GRANT SELECT, INSERT, DELETE ON public.online_country_claims TO authenticated;

CREATE POLICY "country_claims_select"
ON public.online_country_claims FOR SELECT TO authenticated
USING (true);

CREATE POLICY "country_claims_insert"
ON public.online_country_claims FOR INSERT TO authenticated
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "country_claims_delete"
ON public.online_country_claims FOR DELETE TO authenticated
USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS country_claims_user_idx
ON public.online_country_claims(user_id);

CREATE INDEX IF NOT EXISTS country_claims_server_idx
ON public.online_country_claims(server_id);


-- ------------------------------------------------------------
-- 3) SERVER 1 PUBLIC CHAT
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.online_chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    server_id INTEGER NOT NULL DEFAULT 1,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    display_name TEXT NOT NULL DEFAULT 'بازیکن',
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT online_chat_message_length
        CHECK (char_length(trim(message)) BETWEEN 1 AND 300)
);

ALTER TABLE public.online_chat_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "online_chat_select_authenticated" ON public.online_chat_messages;
DROP POLICY IF EXISTS "online_chat_insert_own" ON public.online_chat_messages;

GRANT SELECT, INSERT ON public.online_chat_messages TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.online_chat_messages_id_seq TO authenticated;

CREATE POLICY "online_chat_select_authenticated"
ON public.online_chat_messages FOR SELECT TO authenticated
USING (true);

CREATE POLICY "online_chat_insert_own"
ON public.online_chat_messages FOR INSERT TO authenticated
WITH CHECK (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS online_chat_server_time_idx
ON public.online_chat_messages(server_id, created_at DESC);


-- ------------------------------------------------------------
-- 4) SERVER 1 LEADERBOARD
-- The game updates this row whenever the cloud save is updated.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.online_leaderboard (
    server_id INTEGER NOT NULL DEFAULT 1,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    country_iso TEXT NOT NULL,
    country_name TEXT NOT NULL,
    score BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (server_id, user_id),
    UNIQUE (server_id, country_iso)
);

ALTER TABLE public.online_leaderboard ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "leaderboard_select_authenticated" ON public.online_leaderboard;
DROP POLICY IF EXISTS "leaderboard_insert_own" ON public.online_leaderboard;
DROP POLICY IF EXISTS "leaderboard_update_own" ON public.online_leaderboard;
DROP POLICY IF EXISTS "leaderboard_delete_own" ON public.online_leaderboard;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.online_leaderboard TO authenticated;

CREATE POLICY "leaderboard_select_authenticated"
ON public.online_leaderboard FOR SELECT TO authenticated
USING (true);

CREATE POLICY "leaderboard_insert_own"
ON public.online_leaderboard FOR INSERT TO authenticated
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "leaderboard_update_own"
ON public.online_leaderboard FOR UPDATE TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "leaderboard_delete_own"
ON public.online_leaderboard FOR DELETE TO authenticated
USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS leaderboard_score_idx
ON public.online_leaderboard(server_id, score DESC);


-- ------------------------------------------------------------
-- 5) TWO-SIDED DIPLOMACY REQUESTS
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.diplomacy_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    server_id INTEGER NOT NULL DEFAULT 1,
    requester_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    recipient_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    requester_country_iso TEXT NOT NULL,
    target_country_iso TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('ally','war','peace')),
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending','accepted','rejected','cancelled')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    responded_at TIMESTAMPTZ
);

ALTER TABLE public.diplomacy_requests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "diplomacy_select_participants" ON public.diplomacy_requests;
DROP POLICY IF EXISTS "diplomacy_insert_requester" ON public.diplomacy_requests;
DROP POLICY IF EXISTS "diplomacy_update_recipient" ON public.diplomacy_requests;
DROP POLICY IF EXISTS "diplomacy_delete_requester" ON public.diplomacy_requests;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.diplomacy_requests TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.diplomacy_requests_id_seq TO authenticated;

CREATE POLICY "diplomacy_select_participants"
ON public.diplomacy_requests FOR SELECT TO authenticated
USING (
    auth.uid() = requester_user_id
    OR auth.uid() = recipient_user_id
);

CREATE POLICY "diplomacy_insert_requester"
ON public.diplomacy_requests FOR INSERT TO authenticated
WITH CHECK (
    auth.uid() = requester_user_id
    AND requester_user_id <> recipient_user_id
);

CREATE POLICY "diplomacy_update_recipient"
ON public.diplomacy_requests FOR UPDATE TO authenticated
USING (auth.uid() = recipient_user_id)
WITH CHECK (auth.uid() = recipient_user_id);

CREATE POLICY "diplomacy_delete_requester"
ON public.diplomacy_requests FOR DELETE TO authenticated
USING (auth.uid() = requester_user_id);

CREATE INDEX IF NOT EXISTS diplomacy_recipient_status_idx
ON public.diplomacy_requests(recipient_user_id, status, created_at DESC);

CREATE INDEX IF NOT EXISTS diplomacy_requester_status_idx
ON public.diplomacy_requests(requester_user_id, status, created_at DESC);


-- ------------------------------------------------------------
-- 6) REALTIME FOR CHAT
-- Safe check: add the table only if it is not already published.
-- ------------------------------------------------------------
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime'
    ) AND NOT EXISTS (
        SELECT 1
        FROM pg_publication_tables
        WHERE pubname = 'supabase_realtime'
          AND schemaname = 'public'
          AND tablename = 'online_chat_messages'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.online_chat_messages;
    END IF;
END $$;


-- ============================================================
-- IMPORTANT: LIMITING 2 ACCOUNTS PER IP
-- ============================================================
-- Supabase SQL/RLS cannot reliably see the real client IP during
-- normal browser Auth requests. Do NOT try to enforce an IP limit
-- by trusting an IP value sent from script.js; players can fake it.
-- This requirement needs a Supabase Edge Function (or another
-- trusted server-side signup endpoint) that reads the request IP
-- and counts signups before calling Auth.
-- ============================================================
